-- SumoSim: Migrate wrestler_id from shikona to numeric API ID
-- Generated by tools/migrate_to_api_ids.py
-- Run this in the Supabase SQL Editor

BEGIN;

-- Temporarily disable FK constraints
ALTER TABLE banzuke DROP CONSTRAINT IF EXISTS banzuke_wrestler_id_fkey;
ALTER TABLE tournament_records DROP CONSTRAINT IF EXISTS tournament_records_wrestler_id_fkey;
ALTER TABLE bout_records DROP CONSTRAINT IF EXISTS bout_records_east_id_fkey;
ALTER TABLE bout_records DROP CONSTRAINT IF EXISTS bout_records_west_id_fkey;
ALTER TABLE bout_records DROP CONSTRAINT IF EXISTS bout_records_winner_id_fkey;
ALTER TABLE injury_notes DROP CONSTRAINT IF EXISTS injury_notes_wrestler_id_fkey;

-- Abi: abi -> 22
UPDATE wrestlers SET wrestler_id = '22', api_id = 22, shikona_jp = '阿炎　政虎' WHERE wrestler_id = 'abi';
UPDATE banzuke SET wrestler_id = '22' WHERE wrestler_id = 'abi';
UPDATE tournament_records SET wrestler_id = '22' WHERE wrestler_id = 'abi';
UPDATE bout_records SET east_id = '22' WHERE east_id = 'abi';
UPDATE bout_records SET west_id = '22' WHERE west_id = 'abi';
UPDATE bout_records SET winner_id = '22' WHERE winner_id = 'abi';
UPDATE injury_notes SET wrestler_id = '22' WHERE wrestler_id = 'abi';

-- Aonishiki: aonishiki -> 8854
UPDATE wrestlers SET wrestler_id = '8854', api_id = 8854, shikona_jp = '安青錦　新大' WHERE wrestler_id = 'aonishiki';
UPDATE banzuke SET wrestler_id = '8854' WHERE wrestler_id = 'aonishiki';
UPDATE tournament_records SET wrestler_id = '8854' WHERE wrestler_id = 'aonishiki';
UPDATE bout_records SET east_id = '8854' WHERE east_id = 'aonishiki';
UPDATE bout_records SET west_id = '8854' WHERE west_id = 'aonishiki';
UPDATE bout_records SET winner_id = '8854' WHERE winner_id = 'aonishiki';
UPDATE injury_notes SET wrestler_id = '8854' WHERE wrestler_id = 'aonishiki';

-- Asahakuryu: asahakuryu -> 607
UPDATE wrestlers SET wrestler_id = '607', api_id = 607, shikona_jp = '朝白龍　太郎' WHERE wrestler_id = 'asahakuryu';
UPDATE banzuke SET wrestler_id = '607' WHERE wrestler_id = 'asahakuryu';
UPDATE tournament_records SET wrestler_id = '607' WHERE wrestler_id = 'asahakuryu';
UPDATE bout_records SET east_id = '607' WHERE east_id = 'asahakuryu';
UPDATE bout_records SET west_id = '607' WHERE west_id = 'asahakuryu';
UPDATE bout_records SET winner_id = '607' WHERE winner_id = 'asahakuryu';
UPDATE injury_notes SET wrestler_id = '607' WHERE wrestler_id = 'asahakuryu';

-- Asakoryu: asakoryu -> 164
UPDATE wrestlers SET wrestler_id = '164', api_id = 164, shikona_jp = '朝紅龍　琢馬' WHERE wrestler_id = 'asakoryu';
UPDATE banzuke SET wrestler_id = '164' WHERE wrestler_id = 'asakoryu';
UPDATE tournament_records SET wrestler_id = '164' WHERE wrestler_id = 'asakoryu';
UPDATE bout_records SET east_id = '164' WHERE east_id = 'asakoryu';
UPDATE bout_records SET west_id = '164' WHERE west_id = 'asakoryu';
UPDATE bout_records SET winner_id = '164' WHERE winner_id = 'asakoryu';
UPDATE injury_notes SET wrestler_id = '164' WHERE wrestler_id = 'asakoryu';

-- Asanoyama: asanoyama -> 2
UPDATE wrestlers SET wrestler_id = '2', api_id = 2, shikona_jp = '朝乃山　広暉' WHERE wrestler_id = 'asanoyama';
UPDATE banzuke SET wrestler_id = '2' WHERE wrestler_id = 'asanoyama';
UPDATE tournament_records SET wrestler_id = '2' WHERE wrestler_id = 'asanoyama';
UPDATE bout_records SET east_id = '2' WHERE east_id = 'asanoyama';
UPDATE bout_records SET west_id = '2' WHERE west_id = 'asanoyama';
UPDATE bout_records SET winner_id = '2' WHERE winner_id = 'asanoyama';
UPDATE injury_notes SET wrestler_id = '2' WHERE wrestler_id = 'asanoyama';

-- Atamifuji: atamifuji -> 74
UPDATE wrestlers SET wrestler_id = '74', api_id = 74, shikona_jp = '熱海富士　朔太郎' WHERE wrestler_id = 'atamifuji';
UPDATE banzuke SET wrestler_id = '74' WHERE wrestler_id = 'atamifuji';
UPDATE tournament_records SET wrestler_id = '74' WHERE wrestler_id = 'atamifuji';
UPDATE bout_records SET east_id = '74' WHERE east_id = 'atamifuji';
UPDATE bout_records SET west_id = '74' WHERE west_id = 'atamifuji';
UPDATE bout_records SET winner_id = '74' WHERE winner_id = 'atamifuji';
UPDATE injury_notes SET wrestler_id = '74' WHERE wrestler_id = 'atamifuji';

-- Chiyoshoma: chiyoshoma -> 39
UPDATE wrestlers SET wrestler_id = '39', api_id = 39, shikona_jp = '千代翔馬　富士雄' WHERE wrestler_id = 'chiyoshoma';
UPDATE banzuke SET wrestler_id = '39' WHERE wrestler_id = 'chiyoshoma';
UPDATE tournament_records SET wrestler_id = '39' WHERE wrestler_id = 'chiyoshoma';
UPDATE bout_records SET east_id = '39' WHERE east_id = 'chiyoshoma';
UPDATE bout_records SET west_id = '39' WHERE west_id = 'chiyoshoma';
UPDATE bout_records SET winner_id = '39' WHERE winner_id = 'chiyoshoma';
UPDATE injury_notes SET wrestler_id = '39' WHERE wrestler_id = 'chiyoshoma';

-- Churanoumi: churanoumi -> 71
UPDATE wrestlers SET wrestler_id = '71', api_id = 71, shikona_jp = '美ノ海　義久' WHERE wrestler_id = 'churanoumi';
UPDATE banzuke SET wrestler_id = '71' WHERE wrestler_id = 'churanoumi';
UPDATE tournament_records SET wrestler_id = '71' WHERE wrestler_id = 'churanoumi';
UPDATE bout_records SET east_id = '71' WHERE east_id = 'churanoumi';
UPDATE bout_records SET west_id = '71' WHERE west_id = 'churanoumi';
UPDATE bout_records SET winner_id = '71' WHERE winner_id = 'churanoumi';
UPDATE injury_notes SET wrestler_id = '71' WHERE wrestler_id = 'churanoumi';

-- Daieisho: daieisho -> 9
UPDATE wrestlers SET wrestler_id = '9', api_id = 9, shikona_jp = '大栄翔　勇人' WHERE wrestler_id = 'daieisho';
UPDATE banzuke SET wrestler_id = '9' WHERE wrestler_id = 'daieisho';
UPDATE tournament_records SET wrestler_id = '9' WHERE wrestler_id = 'daieisho';
UPDATE bout_records SET east_id = '9' WHERE east_id = 'daieisho';
UPDATE bout_records SET west_id = '9' WHERE west_id = 'daieisho';
UPDATE bout_records SET winner_id = '9' WHERE winner_id = 'daieisho';
UPDATE injury_notes SET wrestler_id = '9' WHERE wrestler_id = 'daieisho';

-- Fujinokawa: fujinokawa -> 615
UPDATE wrestlers SET wrestler_id = '615', api_id = 615, shikona_jp = '藤ノ川　成剛' WHERE wrestler_id = 'fujinokawa';
UPDATE banzuke SET wrestler_id = '615' WHERE wrestler_id = 'fujinokawa';
UPDATE tournament_records SET wrestler_id = '615' WHERE wrestler_id = 'fujinokawa';
UPDATE bout_records SET east_id = '615' WHERE east_id = 'fujinokawa';
UPDATE bout_records SET west_id = '615' WHERE west_id = 'fujinokawa';
UPDATE bout_records SET winner_id = '615' WHERE winner_id = 'fujinokawa';
UPDATE injury_notes SET wrestler_id = '615' WHERE wrestler_id = 'fujinokawa';

-- Fujiryoga: fujiryoga -> 9051
UPDATE wrestlers SET wrestler_id = '9051', api_id = 9051, shikona_jp = '藤凌駕　雅治' WHERE wrestler_id = 'fujiryoga';
UPDATE banzuke SET wrestler_id = '9051' WHERE wrestler_id = 'fujiryoga';
UPDATE tournament_records SET wrestler_id = '9051' WHERE wrestler_id = 'fujiryoga';
UPDATE bout_records SET east_id = '9051' WHERE east_id = 'fujiryoga';
UPDATE bout_records SET west_id = '9051' WHERE west_id = 'fujiryoga';
UPDATE bout_records SET winner_id = '9051' WHERE winner_id = 'fujiryoga';
UPDATE injury_notes SET wrestler_id = '9051' WHERE wrestler_id = 'fujiryoga';

-- Fujiseiun: fujiseiun -> 82
UPDATE wrestlers SET wrestler_id = '82', api_id = 82, shikona_jp = '藤青雲　龍輝' WHERE wrestler_id = 'fujiseiun';
UPDATE banzuke SET wrestler_id = '82' WHERE wrestler_id = 'fujiseiun';
UPDATE tournament_records SET wrestler_id = '82' WHERE wrestler_id = 'fujiseiun';
UPDATE bout_records SET east_id = '82' WHERE east_id = 'fujiseiun';
UPDATE bout_records SET west_id = '82' WHERE west_id = 'fujiseiun';
UPDATE bout_records SET winner_id = '82' WHERE winner_id = 'fujiseiun';
UPDATE injury_notes SET wrestler_id = '82' WHERE wrestler_id = 'fujiseiun';

-- Gonoyama: gonoyama -> 56
UPDATE wrestlers SET wrestler_id = '56', api_id = 56, shikona_jp = '豪ノ山　登輝' WHERE wrestler_id = 'gonoyama';
UPDATE banzuke SET wrestler_id = '56' WHERE wrestler_id = 'gonoyama';
UPDATE tournament_records SET wrestler_id = '56' WHERE wrestler_id = 'gonoyama';
UPDATE bout_records SET east_id = '56' WHERE east_id = 'gonoyama';
UPDATE bout_records SET west_id = '56' WHERE west_id = 'gonoyama';
UPDATE bout_records SET winner_id = '56' WHERE winner_id = 'gonoyama';
UPDATE injury_notes SET wrestler_id = '56' WHERE wrestler_id = 'gonoyama';

-- Hakunofuji: hakunofuji -> 3
UPDATE wrestlers SET wrestler_id = '3', api_id = 3, shikona_jp = '伯乃富士　哲也' WHERE wrestler_id = 'hakunofuji';
UPDATE banzuke SET wrestler_id = '3' WHERE wrestler_id = 'hakunofuji';
UPDATE tournament_records SET wrestler_id = '3' WHERE wrestler_id = 'hakunofuji';
UPDATE bout_records SET east_id = '3' WHERE east_id = 'hakunofuji';
UPDATE bout_records SET west_id = '3' WHERE west_id = 'hakunofuji';
UPDATE bout_records SET winner_id = '3' WHERE winner_id = 'hakunofuji';
UPDATE injury_notes SET wrestler_id = '3' WHERE wrestler_id = 'hakunofuji';

-- Hiradoumi: hiradoumi -> 24
UPDATE wrestlers SET wrestler_id = '24', api_id = 24, shikona_jp = '平戸海　雄貴' WHERE wrestler_id = 'hiradoumi';
UPDATE banzuke SET wrestler_id = '24' WHERE wrestler_id = 'hiradoumi';
UPDATE tournament_records SET wrestler_id = '24' WHERE wrestler_id = 'hiradoumi';
UPDATE bout_records SET east_id = '24' WHERE east_id = 'hiradoumi';
UPDATE bout_records SET west_id = '24' WHERE west_id = 'hiradoumi';
UPDATE bout_records SET winner_id = '24' WHERE winner_id = 'hiradoumi';
UPDATE injury_notes SET wrestler_id = '24' WHERE wrestler_id = 'hiradoumi';

-- Hoshoryu: hoshoryu -> 19
UPDATE wrestlers SET wrestler_id = '19', api_id = 19, shikona_jp = '豊昇龍　智勝' WHERE wrestler_id = 'hoshoryu';
UPDATE banzuke SET wrestler_id = '19' WHERE wrestler_id = 'hoshoryu';
UPDATE tournament_records SET wrestler_id = '19' WHERE wrestler_id = 'hoshoryu';
UPDATE bout_records SET east_id = '19' WHERE east_id = 'hoshoryu';
UPDATE bout_records SET west_id = '19' WHERE west_id = 'hoshoryu';
UPDATE bout_records SET winner_id = '19' WHERE winner_id = 'hoshoryu';
UPDATE injury_notes SET wrestler_id = '19' WHERE wrestler_id = 'hoshoryu';

-- Ichiyamamoto: ichiyamamoto -> 11
UPDATE wrestlers SET wrestler_id = '11', api_id = 11, shikona_jp = '一山本　大生' WHERE wrestler_id = 'ichiyamamoto';
UPDATE banzuke SET wrestler_id = '11' WHERE wrestler_id = 'ichiyamamoto';
UPDATE tournament_records SET wrestler_id = '11' WHERE wrestler_id = 'ichiyamamoto';
UPDATE bout_records SET east_id = '11' WHERE east_id = 'ichiyamamoto';
UPDATE bout_records SET west_id = '11' WHERE west_id = 'ichiyamamoto';
UPDATE bout_records SET winner_id = '11' WHERE winner_id = 'ichiyamamoto';
UPDATE injury_notes SET wrestler_id = '11' WHERE wrestler_id = 'ichiyamamoto';

-- Kinbozan: kinbozan -> 50
UPDATE wrestlers SET wrestler_id = '50', api_id = 50, shikona_jp = '金峰山　晴樹' WHERE wrestler_id = 'kinbozan';
UPDATE banzuke SET wrestler_id = '50' WHERE wrestler_id = 'kinbozan';
UPDATE tournament_records SET wrestler_id = '50' WHERE wrestler_id = 'kinbozan';
UPDATE bout_records SET east_id = '50' WHERE east_id = 'kinbozan';
UPDATE bout_records SET west_id = '50' WHERE west_id = 'kinbozan';
UPDATE bout_records SET winner_id = '50' WHERE winner_id = 'kinbozan';
UPDATE injury_notes SET wrestler_id = '50' WHERE wrestler_id = 'kinbozan';

-- Kirishima: kirishima -> 7
UPDATE wrestlers SET wrestler_id = '7', api_id = 7, shikona_jp = '霧島　鐵力' WHERE wrestler_id = 'kirishima';
UPDATE banzuke SET wrestler_id = '7' WHERE wrestler_id = 'kirishima';
UPDATE tournament_records SET wrestler_id = '7' WHERE wrestler_id = 'kirishima';
UPDATE bout_records SET east_id = '7' WHERE east_id = 'kirishima';
UPDATE bout_records SET west_id = '7' WHERE west_id = 'kirishima';
UPDATE bout_records SET winner_id = '7' WHERE winner_id = 'kirishima';
UPDATE injury_notes SET wrestler_id = '7' WHERE wrestler_id = 'kirishima';

-- Kotoeiho: kotoeiho -> 112
UPDATE wrestlers SET wrestler_id = '112', api_id = 112, shikona_jp = '琴栄峰　央起' WHERE wrestler_id = 'kotoeiho';
UPDATE banzuke SET wrestler_id = '112' WHERE wrestler_id = 'kotoeiho';
UPDATE tournament_records SET wrestler_id = '112' WHERE wrestler_id = 'kotoeiho';
UPDATE bout_records SET east_id = '112' WHERE east_id = 'kotoeiho';
UPDATE bout_records SET west_id = '112' WHERE west_id = 'kotoeiho';
UPDATE bout_records SET winner_id = '112' WHERE winner_id = 'kotoeiho';
UPDATE injury_notes SET wrestler_id = '112' WHERE wrestler_id = 'kotoeiho';

-- Kotoshoho: kotoshoho -> 8
UPDATE wrestlers SET wrestler_id = '8', api_id = 8, shikona_jp = '琴勝峰　吉成' WHERE wrestler_id = 'kotoshoho';
UPDATE banzuke SET wrestler_id = '8' WHERE wrestler_id = 'kotoshoho';
UPDATE tournament_records SET wrestler_id = '8' WHERE wrestler_id = 'kotoshoho';
UPDATE bout_records SET east_id = '8' WHERE east_id = 'kotoshoho';
UPDATE bout_records SET west_id = '8' WHERE west_id = 'kotoshoho';
UPDATE bout_records SET winner_id = '8' WHERE winner_id = 'kotoshoho';
UPDATE injury_notes SET wrestler_id = '8' WHERE wrestler_id = 'kotoshoho';

-- Kotozakura: kotozakura -> 20
UPDATE wrestlers SET wrestler_id = '20', api_id = 20, shikona_jp = '琴櫻　将傑' WHERE wrestler_id = 'kotozakura';
UPDATE banzuke SET wrestler_id = '20' WHERE wrestler_id = 'kotozakura';
UPDATE tournament_records SET wrestler_id = '20' WHERE wrestler_id = 'kotozakura';
UPDATE bout_records SET east_id = '20' WHERE east_id = 'kotozakura';
UPDATE bout_records SET west_id = '20' WHERE west_id = 'kotozakura';
UPDATE bout_records SET winner_id = '20' WHERE winner_id = 'kotozakura';
UPDATE injury_notes SET wrestler_id = '20' WHERE wrestler_id = 'kotozakura';

-- Midorifuji: midorifuji -> 34
UPDATE wrestlers SET wrestler_id = '34', api_id = 34, shikona_jp = '翠富士　一成' WHERE wrestler_id = 'midorifuji';
UPDATE banzuke SET wrestler_id = '34' WHERE wrestler_id = 'midorifuji';
UPDATE tournament_records SET wrestler_id = '34' WHERE wrestler_id = 'midorifuji';
UPDATE bout_records SET east_id = '34' WHERE east_id = 'midorifuji';
UPDATE bout_records SET west_id = '34' WHERE west_id = 'midorifuji';
UPDATE bout_records SET winner_id = '34' WHERE winner_id = 'midorifuji';
UPDATE injury_notes SET wrestler_id = '34' WHERE wrestler_id = 'midorifuji';

-- Mitakeumi: mitakeumi -> 26
UPDATE wrestlers SET wrestler_id = '26', api_id = 26, shikona_jp = '御嶽海　久司' WHERE wrestler_id = 'mitakeumi';
UPDATE banzuke SET wrestler_id = '26' WHERE wrestler_id = 'mitakeumi';
UPDATE tournament_records SET wrestler_id = '26' WHERE wrestler_id = 'mitakeumi';
UPDATE bout_records SET east_id = '26' WHERE east_id = 'mitakeumi';
UPDATE bout_records SET west_id = '26' WHERE west_id = 'mitakeumi';
UPDATE bout_records SET winner_id = '26' WHERE winner_id = 'mitakeumi';
UPDATE injury_notes SET wrestler_id = '26' WHERE wrestler_id = 'mitakeumi';

-- Nishikifuji: nishikifuji -> 40
UPDATE wrestlers SET wrestler_id = '40', api_id = 40, shikona_jp = '錦富士　隆聖' WHERE wrestler_id = 'nishikifuji';
UPDATE banzuke SET wrestler_id = '40' WHERE wrestler_id = 'nishikifuji';
UPDATE tournament_records SET wrestler_id = '40' WHERE wrestler_id = 'nishikifuji';
UPDATE bout_records SET east_id = '40' WHERE east_id = 'nishikifuji';
UPDATE bout_records SET west_id = '40' WHERE west_id = 'nishikifuji';
UPDATE bout_records SET winner_id = '40' WHERE winner_id = 'nishikifuji';
UPDATE injury_notes SET wrestler_id = '40' WHERE wrestler_id = 'nishikifuji';

-- Oho: oho -> 41
UPDATE wrestlers SET wrestler_id = '41', api_id = 41, shikona_jp = '王鵬　幸之介' WHERE wrestler_id = 'oho';
UPDATE banzuke SET wrestler_id = '41' WHERE wrestler_id = 'oho';
UPDATE tournament_records SET wrestler_id = '41' WHERE wrestler_id = 'oho';
UPDATE bout_records SET east_id = '41' WHERE east_id = 'oho';
UPDATE bout_records SET west_id = '41' WHERE west_id = 'oho';
UPDATE bout_records SET winner_id = '41' WHERE winner_id = 'oho';
UPDATE injury_notes SET wrestler_id = '41' WHERE wrestler_id = 'oho';

-- Onokatsu: onokatsu -> 8853
UPDATE wrestlers SET wrestler_id = '8853', api_id = 8853, shikona_jp = '阿武剋　一弘' WHERE wrestler_id = 'onokatsu';
UPDATE banzuke SET wrestler_id = '8853' WHERE wrestler_id = 'onokatsu';
UPDATE tournament_records SET wrestler_id = '8853' WHERE wrestler_id = 'onokatsu';
UPDATE bout_records SET east_id = '8853' WHERE east_id = 'onokatsu';
UPDATE bout_records SET west_id = '8853' WHERE west_id = 'onokatsu';
UPDATE bout_records SET winner_id = '8853' WHERE winner_id = 'onokatsu';
UPDATE injury_notes SET wrestler_id = '8853' WHERE wrestler_id = 'onokatsu';

-- Onosato: onosato -> 8850
UPDATE wrestlers SET wrestler_id = '8850', api_id = 8850, shikona_jp = '大の里　泰輝' WHERE wrestler_id = 'onosato';
UPDATE banzuke SET wrestler_id = '8850' WHERE wrestler_id = 'onosato';
UPDATE tournament_records SET wrestler_id = '8850' WHERE wrestler_id = 'onosato';
UPDATE bout_records SET east_id = '8850' WHERE east_id = 'onosato';
UPDATE bout_records SET west_id = '8850' WHERE west_id = 'onosato';
UPDATE bout_records SET winner_id = '8850' WHERE winner_id = 'onosato';
UPDATE injury_notes SET wrestler_id = '8850' WHERE wrestler_id = 'onosato';

-- Oshoma: oshoma -> 61
UPDATE wrestlers SET wrestler_id = '61', api_id = 61, shikona_jp = '欧勝馬　出気' WHERE wrestler_id = 'oshoma';
UPDATE banzuke SET wrestler_id = '61' WHERE wrestler_id = 'oshoma';
UPDATE tournament_records SET wrestler_id = '61' WHERE wrestler_id = 'oshoma';
UPDATE bout_records SET east_id = '61' WHERE east_id = 'oshoma';
UPDATE bout_records SET west_id = '61' WHERE west_id = 'oshoma';
UPDATE bout_records SET winner_id = '61' WHERE winner_id = 'oshoma';
UPDATE injury_notes SET wrestler_id = '61' WHERE wrestler_id = 'oshoma';

-- Oshoumi: oshoumi -> 95
UPDATE wrestlers SET wrestler_id = '95', api_id = 95, shikona_jp = '欧勝海　成矢' WHERE wrestler_id = 'oshoumi';
UPDATE banzuke SET wrestler_id = '95' WHERE wrestler_id = 'oshoumi';
UPDATE tournament_records SET wrestler_id = '95' WHERE wrestler_id = 'oshoumi';
UPDATE bout_records SET east_id = '95' WHERE east_id = 'oshoumi';
UPDATE bout_records SET west_id = '95' WHERE west_id = 'oshoumi';
UPDATE bout_records SET winner_id = '95' WHERE winner_id = 'oshoumi';
UPDATE injury_notes SET wrestler_id = '95' WHERE wrestler_id = 'oshoumi';

-- Roga: roga -> 55
UPDATE wrestlers SET wrestler_id = '55', api_id = 55, shikona_jp = '狼雅　外喜義' WHERE wrestler_id = 'roga';
UPDATE banzuke SET wrestler_id = '55' WHERE wrestler_id = 'roga';
UPDATE tournament_records SET wrestler_id = '55' WHERE wrestler_id = 'roga';
UPDATE bout_records SET east_id = '55' WHERE east_id = 'roga';
UPDATE bout_records SET west_id = '55' WHERE west_id = 'roga';
UPDATE bout_records SET winner_id = '55' WHERE winner_id = 'roga';
UPDATE injury_notes SET wrestler_id = '55' WHERE wrestler_id = 'roga';

-- Shishi: shishi -> 86
UPDATE wrestlers SET wrestler_id = '86', api_id = 86, shikona_jp = '獅司　大' WHERE wrestler_id = 'shishi';
UPDATE banzuke SET wrestler_id = '86' WHERE wrestler_id = 'shishi';
UPDATE tournament_records SET wrestler_id = '86' WHERE wrestler_id = 'shishi';
UPDATE bout_records SET east_id = '86' WHERE east_id = 'shishi';
UPDATE bout_records SET west_id = '86' WHERE west_id = 'shishi';
UPDATE bout_records SET winner_id = '86' WHERE winner_id = 'shishi';
UPDATE injury_notes SET wrestler_id = '86' WHERE wrestler_id = 'shishi';

-- Shodai: shodai -> 33
UPDATE wrestlers SET wrestler_id = '33', api_id = 33, shikona_jp = '正代　直也' WHERE wrestler_id = 'shodai';
UPDATE banzuke SET wrestler_id = '33' WHERE wrestler_id = 'shodai';
UPDATE tournament_records SET wrestler_id = '33' WHERE wrestler_id = 'shodai';
UPDATE bout_records SET east_id = '33' WHERE east_id = 'shodai';
UPDATE bout_records SET west_id = '33' WHERE west_id = 'shodai';
UPDATE bout_records SET winner_id = '33' WHERE winner_id = 'shodai';
UPDATE injury_notes SET wrestler_id = '33' WHERE wrestler_id = 'shodai';

-- Takanosho: takanosho -> 37
UPDATE wrestlers SET wrestler_id = '37', api_id = 37, shikona_jp = '隆の勝　伸明' WHERE wrestler_id = 'takanosho';
UPDATE banzuke SET wrestler_id = '37' WHERE wrestler_id = 'takanosho';
UPDATE tournament_records SET wrestler_id = '37' WHERE wrestler_id = 'takanosho';
UPDATE bout_records SET east_id = '37' WHERE east_id = 'takanosho';
UPDATE bout_records SET west_id = '37' WHERE west_id = 'takanosho';
UPDATE bout_records SET winner_id = '37' WHERE winner_id = 'takanosho';
UPDATE injury_notes SET wrestler_id = '37' WHERE wrestler_id = 'takanosho';

-- Takayasu: takayasu -> 44
UPDATE wrestlers SET wrestler_id = '44', api_id = 44, shikona_jp = '高安　晃' WHERE wrestler_id = 'takayasu';
UPDATE banzuke SET wrestler_id = '44' WHERE wrestler_id = 'takayasu';
UPDATE tournament_records SET wrestler_id = '44' WHERE wrestler_id = 'takayasu';
UPDATE bout_records SET east_id = '44' WHERE east_id = 'takayasu';
UPDATE bout_records SET west_id = '44' WHERE west_id = 'takayasu';
UPDATE bout_records SET winner_id = '44' WHERE winner_id = 'takayasu';
UPDATE injury_notes SET wrestler_id = '44' WHERE wrestler_id = 'takayasu';

-- Tamawashi: tamawashi -> 14
UPDATE wrestlers SET wrestler_id = '14', api_id = 14, shikona_jp = '玉鷲　一朗' WHERE wrestler_id = 'tamawashi';
UPDATE banzuke SET wrestler_id = '14' WHERE wrestler_id = 'tamawashi';
UPDATE tournament_records SET wrestler_id = '14' WHERE wrestler_id = 'tamawashi';
UPDATE bout_records SET east_id = '14' WHERE east_id = 'tamawashi';
UPDATE bout_records SET west_id = '14' WHERE west_id = 'tamawashi';
UPDATE bout_records SET winner_id = '14' WHERE winner_id = 'tamawashi';
UPDATE injury_notes SET wrestler_id = '14' WHERE wrestler_id = 'tamawashi';

-- Tobizaru: tobizaru -> 21
UPDATE wrestlers SET wrestler_id = '21', api_id = 21, shikona_jp = '翔猿　正也' WHERE wrestler_id = 'tobizaru';
UPDATE banzuke SET wrestler_id = '21' WHERE wrestler_id = 'tobizaru';
UPDATE tournament_records SET wrestler_id = '21' WHERE wrestler_id = 'tobizaru';
UPDATE bout_records SET east_id = '21' WHERE east_id = 'tobizaru';
UPDATE bout_records SET west_id = '21' WHERE west_id = 'tobizaru';
UPDATE bout_records SET winner_id = '21' WHERE winner_id = 'tobizaru';
UPDATE injury_notes SET wrestler_id = '21' WHERE wrestler_id = 'tobizaru';

-- Tokihayate: tokihayate -> 83
UPDATE wrestlers SET wrestler_id = '83', api_id = 83, shikona_jp = '時疾風　秀喜' WHERE wrestler_id = 'tokihayate';
UPDATE banzuke SET wrestler_id = '83' WHERE wrestler_id = 'tokihayate';
UPDATE tournament_records SET wrestler_id = '83' WHERE wrestler_id = 'tokihayate';
UPDATE bout_records SET east_id = '83' WHERE east_id = 'tokihayate';
UPDATE bout_records SET west_id = '83' WHERE west_id = 'tokihayate';
UPDATE bout_records SET winner_id = '83' WHERE winner_id = 'tokihayate';
UPDATE injury_notes SET wrestler_id = '83' WHERE wrestler_id = 'tokihayate';

-- Ura: ura -> 28
UPDATE wrestlers SET wrestler_id = '28', api_id = 28, shikona_jp = '宇良　和輝' WHERE wrestler_id = 'ura';
UPDATE banzuke SET wrestler_id = '28' WHERE wrestler_id = 'ura';
UPDATE tournament_records SET wrestler_id = '28' WHERE wrestler_id = 'ura';
UPDATE bout_records SET east_id = '28' WHERE east_id = 'ura';
UPDATE bout_records SET west_id = '28' WHERE west_id = 'ura';
UPDATE bout_records SET winner_id = '28' WHERE winner_id = 'ura';
UPDATE injury_notes SET wrestler_id = '28' WHERE wrestler_id = 'ura';

-- Wakamotoharu: wakamotoharu -> 13
UPDATE wrestlers SET wrestler_id = '13', api_id = 13, shikona_jp = '若元春　港' WHERE wrestler_id = 'wakamotoharu';
UPDATE banzuke SET wrestler_id = '13' WHERE wrestler_id = 'wakamotoharu';
UPDATE tournament_records SET wrestler_id = '13' WHERE wrestler_id = 'wakamotoharu';
UPDATE bout_records SET east_id = '13' WHERE east_id = 'wakamotoharu';
UPDATE bout_records SET west_id = '13' WHERE west_id = 'wakamotoharu';
UPDATE bout_records SET winner_id = '13' WHERE winner_id = 'wakamotoharu';
UPDATE injury_notes SET wrestler_id = '13' WHERE wrestler_id = 'wakamotoharu';

-- Wakatakakage: wakatakakage -> 12
UPDATE wrestlers SET wrestler_id = '12', api_id = 12, shikona_jp = '若隆景　渥' WHERE wrestler_id = 'wakatakakage';
UPDATE banzuke SET wrestler_id = '12' WHERE wrestler_id = 'wakatakakage';
UPDATE tournament_records SET wrestler_id = '12' WHERE wrestler_id = 'wakatakakage';
UPDATE bout_records SET east_id = '12' WHERE east_id = 'wakatakakage';
UPDATE bout_records SET west_id = '12' WHERE west_id = 'wakatakakage';
UPDATE bout_records SET winner_id = '12' WHERE winner_id = 'wakatakakage';
UPDATE injury_notes SET wrestler_id = '12' WHERE wrestler_id = 'wakatakakage';

-- Yoshinofuji: yoshinofuji -> 8857
UPDATE wrestlers SET wrestler_id = '8857', api_id = 8857, shikona_jp = '義ノ富士　直哉' WHERE wrestler_id = 'yoshinofuji';
UPDATE banzuke SET wrestler_id = '8857' WHERE wrestler_id = 'yoshinofuji';
UPDATE tournament_records SET wrestler_id = '8857' WHERE wrestler_id = 'yoshinofuji';
UPDATE bout_records SET east_id = '8857' WHERE east_id = 'yoshinofuji';
UPDATE bout_records SET west_id = '8857' WHERE west_id = 'yoshinofuji';
UPDATE bout_records SET winner_id = '8857' WHERE winner_id = 'yoshinofuji';
UPDATE injury_notes SET wrestler_id = '8857' WHERE wrestler_id = 'yoshinofuji';

-- Restore FK constraints
ALTER TABLE banzuke ADD CONSTRAINT banzuke_wrestler_id_fkey FOREIGN KEY (wrestler_id) REFERENCES wrestlers(wrestler_id);
ALTER TABLE tournament_records ADD CONSTRAINT tournament_records_wrestler_id_fkey FOREIGN KEY (wrestler_id) REFERENCES wrestlers(wrestler_id);
ALTER TABLE bout_records ADD CONSTRAINT bout_records_east_id_fkey FOREIGN KEY (east_id) REFERENCES wrestlers(wrestler_id);
ALTER TABLE bout_records ADD CONSTRAINT bout_records_west_id_fkey FOREIGN KEY (west_id) REFERENCES wrestlers(wrestler_id);
ALTER TABLE bout_records ADD CONSTRAINT bout_records_winner_id_fkey FOREIGN KEY (winner_id) REFERENCES wrestlers(wrestler_id);
ALTER TABLE injury_notes ADD CONSTRAINT injury_notes_wrestler_id_fkey FOREIGN KEY (wrestler_id) REFERENCES wrestlers(wrestler_id);

COMMIT;